name: 'coverage'
on:
    pull_request_target:
        branches:
            - master
            - main
permissions:
    id-token: write
jobs:


    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2